import Head from "next/head";
import React from "react";
import dynamic from "next/dynamic";
const OtherMap = dynamic(() => import("@/components/OtherMap"), {
  ssr: false,
  loading: () => "Loading...",
});
const TestMap = () => {
  return (
    <>
      <Head>
        <title>OtherMap</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <OtherMap />
      </main>
    </>
  );
};

export default TestMap;
